<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="FB_PID_EXT" Id="{c05f2f87-9880-4b09-b5b5-0a395cb1c163}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PID_EXT EXTENDS FB_BasicPID
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_PID_EXT">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>