<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="F_AxisRef_To_MSTA" Id="{6037187c-3053-436d-ba08-ac7db25710cf}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_AxisRef_To_MSTA	: UINT
VAR_INPUT
    stManipAxis	:	ST_ManipAxis;
END_VAR
VAR_OUTPUT
    MSTA	:	UINT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* This block translates the axis ref status to an EPICS psuedo MSTA value *)
(* A. Wallace, 17/8/17 *)

MSTA.1 := stManipAxis.stAxis.Status.Error;
MSTA.0 := stManipAxis.xEnabled;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>