<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="SerialTxRx" Id="{8ce33525-cb60-4010-bca4-10eb26b43a58}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM SerialTxRx
VAR
(*	
	fbSerialLineControl_M2SelAVici: SerialLineControl;
	fbSerialLineControl_M2SelBVici: SerialLineControl;
	fbSerialLineControl_M2SelAFM: SerialLineControl;
	fbSerialLineControl_M2SelBFM: SerialLineControl;
	
	fbSerialLineControl_M3SelAVici: SerialLineControl;
	fbSerialLineControl_M3SelAFM: SerialLineControl;
	fbSerialLineControl_M3SelBVici: SerialLineControl;
	fbSerialLineControl_M3SelBFM: SerialLineControl;
*)
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

M3SelectorA.SerialComm();

PCMA.SerialComm();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>